name: CI

on:
  pull_request:
    branches: 
      -main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: 18.12.1
        - name: Install Dependencies
          run: npm install
        - name: Run Tests
          env:
           BROWSERSTACK_USERNAME: ${{ secrets.BS_USER }}
           BROWSERSTACK_ACCESS_KEY: ${{ secrets.BS_KEY }}
          # run: npm run test:local
          run: npm run test-browserstack
          # npx wdio config/wdio.android.bs.conf.ts --spec specs/products/purchaseProduct.test.ts
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs
 